#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/Drive.h"
#include "commands/TelescopeExtend.h"
#include <frc2/command/button/JoystickButton.h>
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
driveStick = new frc::Joystick(0);
systemStick = new frc::Joystick(1);
//One-joystick control quickfix. For readability/clarity, remove systemStick and reassign all of the commands to driveStick (which will be renamed for clarity aswell- perhaps "mainStick"?  
    // SmartDashboard Buttons
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
TelescopeExtendButton = new frc2::JoystickButton(systemStick, 8); 
}


frc::Joystick* OI::getDriveStick() {
   return driveStick;
}
frc::Joystick* OI::getSystemStick(){
    return systemStick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS