// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/PneumaticsArm.h"
#include <frc/smartdashboard/SmartDashboard.h>

#include <stdio.h>
#include <iostream>
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

PneumaticsArm::PneumaticsArm(){
     ///frc::Solenoid* STUPID = &Solenoid11;
    SetName("PneumaticsArm");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("PneumaticsArm");



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void PneumaticsArm::Periodic() {
    // Put code here to be run every loop

}

void PneumaticsArm::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}
// @param channel1 The first channel that the double solenoid is hooked up to
// @param channel2 The second channel that the double solenoid is hooked up to
void PneumaticsArm::ExtendArm() {
    ArmSolenoid.Set(frc::DoubleSolenoid::kForward);
}

void PneumaticsArm::RetractArm() {
    ArmSolenoid.Set(frc::DoubleSolenoid::kReverse);
}
void PneumaticsArm::Closer() {
        ArmSolenoid.Set(frc::DoubleSolenoid::kOff);
}
