// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/PneumaticsGrabber.h"
#include <frc/smartdashboard/SmartDashboard.h>

#include <stdio.h>
#include <iostream>
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

PneumaticsGrabber::PneumaticsGrabber(){
     ///frc::Solenoid* STUPID = &Solenoid11;
    SetName("PneumaticsGrabber");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("PneumaticsGrabber");



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void PneumaticsGrabber::Periodic() {
    // Put code here to be run every loop

}

void PneumaticsGrabber::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

 void PneumaticsGrabber::Grab() {
    GrabberSolenoid.Set(frc::DoubleSolenoid::kForward);
 }




  void PneumaticsGrabber::UnGrab() {
    GrabberSolenoid.Set(frc::DoubleSolenoid::kReverse);
  }

